### ISSUE TITLE
Form 

### ISSUE THREAD

**Issue by youngxpak** [hannalip/Group-Project-01#4]
Check boxes
What do you want? salty? sweet? savory? ect

**Comment by zfrakes** [comment]
*1st Prompt 
Dine in or pick up?(delivery option)

*2nd Prompt (meal type 
Breakfast 
Brunch
Lunch 
Dinner 
*3rd  Prompt (taste type)
Sweet 
Savory 
Salty 
Healthy
Comfort 

*4th Fourth Prompt (cuisines type)(optional)
American
Asian( Korean,Japanese,Thai, Chinese, vietnamese)
Bakery 
Breakfast( Coffee)
Dessert
Fast Food
Indian 
Italian 
Mediterranean 
Mexican 
Seafood 
Vegetarian 

*5th Prompt ( number of options)

  1-10

**Comment by youngxpak** [comment]
love this! but I was thinking like instead of giving the type of cuisine... give like food options like "i'm craving something with shrimp" or "I'm craving something fresh and light"

the 5th prompt I think the options should be limited to 5, well technically 4 and the 5th can be "start over". Because giving so many options makes the app useless and makes us once again indecisive. 
if it gets too hard/ complicated then we can go back to this. We can do a group vote. 


Also looking forward to seeing everyone on thursday! Happy New Year yall!

**Comment by hannalip** [comment]
When we were trying it up we did it as a "phase 1" questionnaire to get us started with general questions also bc we don't know what the APIs we are using yet. But as we have a working application we can enhance it through the phases to get it to have specific things like "I'm craving something with shrimp"
