### ISSUE TITLE
Ryan Gif

### ISSUE THREAD

**Issue by zfrakes** [hannalip/Group-Project-01#5]
Head page- Gif of Ryan Gislon ( what do you want ?) will faded out

**Comment by youngxpak** [comment]
Wait you mean Ryan Gosling right? yeah, i think when the app opens it's a gif of him doing "WHAT DO YOU WANT?" And yes the fade out into the first prompt

**Comment by hannalip** [comment]
lol yes Ryan Gosling

**Comment by youngxpak** [comment]
ppt
